development:
  password: shptka_1f50310f8895d31c473c7047e503aa73
  theme_id: '149102395702'
  store: fabula-tabs.myshopify.com
  ignore_files:
    - /\.(txt|gif|bat)$/
    - '*.liquid___jb_tmp___'
    - '*.liquid___jb_old___'